name: AlphaSystem
version: 1.3.3
api-version: 1.13
main: cc.nuym.alphasystem.AlphaSystem
commands:
  infraction:
    description: Apply infractions #%%__USER__%%
    aliases:
      - infractions
      - inf
  alphasystem:
    description: Main command
